-- public.catalogue definition

-- Drop table

-- DROP TABLE public.catalogue;

CREATE TABLE public.catalogue (
	id int8 NOT NULL,
	details jsonb NULL,
	CONSTRAINT catalogue_pkey PRIMARY KEY (id)
);


-- public.deployment_environment definition

-- Drop table

-- DROP TABLE public.deployment_environment;

CREATE TABLE public.deployment_environment (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT deployment_environment_pkey PRIMARY KEY (id)
);


-- public.micro_service definition

-- Drop table

-- DROP TABLE public.micro_service;

CREATE TABLE public.micro_service (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	department varchar(255) NULL,
	product varchar(255) NULL,
	environment varchar(20) NULL,
	service_type varchar(20) NULL,
	service_topology jsonb NULL,
	business_location jsonb NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	compliance_json jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT micro_service_pkey PRIMARY KEY (id)
);


-- public.organization definition

-- Drop table

-- DROP TABLE public.organization;

CREATE TABLE public.organization (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT organization_pkey PRIMARY KEY (id)
);


-- public.department definition

-- Drop table

-- DROP TABLE public.department;

CREATE TABLE public.department (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	organization_id int8 NULL,
	CONSTRAINT department_pkey PRIMARY KEY (id),
	CONSTRAINT fk_department__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.cloud_environment definition

-- Drop table

-- DROP TABLE public.cloud_environment;

CREATE TABLE public.cloud_environment (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	description varchar(5000) NULL,
	account_id varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	department_id int8 NULL,
	display_name varchar(255) NULL,
	role_arn varchar(255) NULL,
	external_id varchar(255) NULL,
	cloud varchar(255) NULL,
	CONSTRAINT cloud_environment_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_environment__department_id FOREIGN KEY (department_id) REFERENCES public.department(id)
);


-- public.cloud_element definition

-- Drop table

-- DROP TABLE public.cloud_element;

CREATE TABLE public.cloud_element (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	instance_id varchar(255) NULL,
	element_type varchar(255) NULL,
	arn varchar(255) NULL,
	cloud_entity jsonb NULL,
	hardware_location jsonb NULL,
	hosted_services jsonb NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	compliance_json jsonb NULL,
	tag_status varchar(20) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	cloud_environment_id int8 NULL,
	CONSTRAINT cloud_element_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element__cloud_environment_id FOREIGN KEY (cloud_environment_id) REFERENCES public.cloud_environment(id)
);


-- public.cloud_element_summary definition

-- Drop table

-- DROP TABLE public.cloud_element_summary;

CREATE TABLE public.cloud_element_summary (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	summary_json jsonb NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	cloud_environment_id int8 NULL,
	CONSTRAINT cloud_element_summary_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element_summary__cloud_environment_id FOREIGN KEY (cloud_environment_id) REFERENCES public.cloud_environment(id)
);