CREATE TABLE public.organization (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	security_service_org_id int8 NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT organization_pkey PRIMARY KEY (id)
);

CREATE TABLE public.db_category (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	organization_id int8 NULL,
	status varchar(255) null default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT db_category_pkey PRIMARY KEY (id),
	CONSTRAINT fk_db_category__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);

CREATE TABLE public.budget (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	allocated_budget int8 NULL,
	budget_json jsonb NULL,
	organization_id int8 NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT budget_pkey PRIMARY KEY (id),
	CONSTRAINT fk_budget__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);

CREATE TABLE public.department (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	organization_id int8 NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT department_pkey PRIMARY KEY (id),
	CONSTRAINT fk_department__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);

CREATE TABLE public.product (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	"type" varchar(255) NOT NULL,
	organization_id int8 NULL,
	department_id int8 NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id),
	CONSTRAINT fk_product__department_id FOREIGN KEY (department_id) REFERENCES public.department(id)
);

CREATE TABLE public.landingzone (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	description varchar(5000) NULL,
	landing_zone varchar(255) NULL,
	department_id int8 NULL,
	cloud varchar(255) NULL,
	display_name varchar(255) NULL,
	role_arn varchar(255) NULL,
	external_id varchar(255) NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT landingzone_pkey PRIMARY KEY (id),
	CONSTRAINT fk_landingzone__department_id FOREIGN KEY (department_id) REFERENCES public.department(id)
);

CREATE TABLE public.product_enclave (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	instance_name varchar(255) NOT NULL,
	instance_id varchar(255) NOT NULL,
	landing_zone varchar(255) NULL,
	state varchar(100) NULL,
	metadata jsonb NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	department_id int8 NULL,
	CONSTRAINT product_enclave_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product_enclave__department_id FOREIGN KEY (department_id) REFERENCES public.department(id)
);

CREATE TABLE public.product_env (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NULL,
	product_id int8 NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT product_env_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product_env__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);

CREATE TABLE public.cloud_element_summary (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	summary_json jsonb NULL,
	landingzone_id int8 NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT cloud_element_summary_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element_summary__landingzone_id FOREIGN KEY (landingzone_id) REFERENCES public.landingzone(id)
);

CREATE TABLE public.cloud_element (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	element_type varchar(255) NULL,
	hosted_services jsonb NULL,
	arn varchar(255) NULL,
	instance_id varchar(255) NULL,
	instance_name varchar(255) NULL,
	category varchar(20) NULL,
	landingzone_id int8 NULL,
	db_category_id int8 NULL,
	product_enclave_id int8 NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	compliance_json jsonb NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT cloud_element_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element__landingzone_id FOREIGN KEY (landingzone_id) REFERENCES public.landingzone(id),
	CONSTRAINT fk_cloud_element__product_enclave_id FOREIGN KEY (product_enclave_id) REFERENCES public.product_enclave(id),
	CONSTRAINT fk_cloud_element__db_category_id FOREIGN KEY (db_category_id) REFERENCES public.db_category(id)
);

CREATE TABLE public."module" (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"name" varchar(255) NOT NULL,
	product_id int8 NULL,
	product_env_id int8 NULL,
	module_nature varchar(20) NULL,
	service_topology jsonb NULL,
	metadata jsonb NULL,
	status varchar(255) null default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT module_pkey PRIMARY KEY (id),
	CONSTRAINT fk_module__product_env_id FOREIGN KEY (product_env_id) REFERENCES public.product_env(id),
	CONSTRAINT fk_module__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);

CREATE TABLE public.business_element (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	service_name varchar(255) NOT NULL,
	service_nature varchar(20) NULL,
	service_type varchar(20) NULL,
	metadata jsonb NULL,
	cloud_element_id int8 NULL,
	department_id int8 NULL,
	product_id int8 NULL,
	module_id int8 NULL,
	product_env_id int8 NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	compliance_json jsonb NULL,
	status varchar(255) NULL default 'Active',
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT business_element_pkey PRIMARY KEY (id),
	CONSTRAINT fk_business_element__cloud_element_id FOREIGN KEY (cloud_element_id) REFERENCES public.cloud_element(id),
	CONSTRAINT fk_business_element__department_id FOREIGN KEY (department_id) REFERENCES public.department(id),
	CONSTRAINT fk_business_element__module_id FOREIGN KEY (module_id) REFERENCES public."module"(id),
	CONSTRAINT fk_business_element__product_env_id FOREIGN KEY (product_env_id) REFERENCES public.product_env(id),
	CONSTRAINT fk_business_element__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);

