-- public.bi_service definition

-- Drop table

-- DROP TABLE public.bi_service;

CREATE TABLE public.bi_service (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	product_category varchar(255) NULL,
	service_category varchar(255) NULL,
	"name" varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	service_type varchar(255) NULL,
	service_module varchar(255) NULL,
	CONSTRAINT bi_service_pkey PRIMARY KEY (id)
);


-- public.cloud definition

-- Drop table

-- DROP TABLE public.cloud;

CREATE TABLE public.cloud (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	element_type varchar(255) NULL,
	"name" varchar(255) NULL,
	is_cron_scheduled bool DEFAULT false NULL,
	list_query varchar(255) NULL,
	config_query varchar(255) NULL,
	config_key varchar(50) NULL,
	ui_mapping jsonb NULL,
	status varchar(255) NULL,
	service_category varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT cloud_pkey PRIMARY KEY (id)
);


-- public.cloud_element_supported_api definition

-- Drop table

-- DROP TABLE public.cloud_element_supported_api;

CREATE TABLE public.cloud_element_supported_api (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cloud varchar(255) NULL,
	element_type varchar(255) NULL,
	"name" varchar(255) NULL,
	status varchar(255) DEFAULT 'ACTIVE'::character varying NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	frames varchar(10000) NULL,
	CONSTRAINT supported_element_api_pkey PRIMARY KEY (id)
);

-- public.organization definition

-- Drop table

-- DROP TABLE public.organization;

CREATE TABLE public.organization (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	security_service_org_id int8 NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	CONSTRAINT organization_pkey PRIMARY KEY (id)
);


-- public.service_queue definition

-- Drop table

-- DROP TABLE public.service_queue;

CREATE TABLE public.service_queue (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"key" varchar(255) NULL,
	value varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	organization_id int8 NULL,
	CONSTRAINT service_queue_pkey PRIMARY KEY (id)
);


-- public.budget definition

-- Drop table

-- DROP TABLE public.budget;

CREATE TABLE public.budget (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	allocated_budget int8 NULL,
	budget_json jsonb NULL,
	organization_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	financial_year_start date NULL,
	financial_year_end date NULL,
	CONSTRAINT budget_pkey PRIMARY KEY (id),
	CONSTRAINT fk_budget__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.config definition

-- Drop table

-- DROP TABLE public.config;

CREATE TABLE public.config (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"key" varchar(255) NULL,
	value varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	organization_id int8 NULL,
	is_encrypted bool DEFAULT false NULL,
	CONSTRAINT config_pkey PRIMARY KEY (id),
	CONSTRAINT fk_config__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.db_category definition

-- Drop table

-- DROP TABLE public.db_category;

CREATE TABLE public.db_category (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	organization_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT db_category_pkey PRIMARY KEY (id),
	CONSTRAINT fk_db_category__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.department definition

-- Drop table

-- DROP TABLE public.department;

CREATE TABLE public.department (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	organization_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	created_by varchar(255) NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	description varchar(2000) NULL,
	CONSTRAINT department_pkey PRIMARY KEY (id),
	CONSTRAINT fk_department__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.landingzone definition

-- Drop table

-- DROP TABLE public.landingzone;

CREATE TABLE public.landingzone (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description varchar(5000) NULL,
	landing_zone varchar(255) NULL,
	department_id int8 NULL,
	cloud varchar(255) NULL,
	display_name varchar(255) NULL,
	role_arn varchar(255) NULL,
	external_id varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	organization_id int8 NULL,
	CONSTRAINT landingzone_pkey PRIMARY KEY (id),
	CONSTRAINT fk_landingzone__department_id FOREIGN KEY (department_id) REFERENCES public.department(id)
);


-- public.product definition

-- Drop table

-- DROP TABLE public.product;

CREATE TABLE public.product (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	"type" varchar(255) NOT NULL,
	organization_id int8 NULL,
	department_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT product_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product__department_id FOREIGN KEY (department_id) REFERENCES public.department(id),
	CONSTRAINT fk_product__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);


-- public.product_enclave definition

-- Drop table

-- DROP TABLE public.product_enclave;

CREATE TABLE public.product_enclave (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	instance_name varchar(255) NOT NULL,
	instance_id varchar(255) NOT NULL,
	state varchar(100) NULL,
	metadata jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	department_id int8 NULL,
	landingzone_id int8 NULL,
	service_category varchar(255) NULL,
	region varchar(255) NULL,
	log_group varchar(255) NULL,
	CONSTRAINT product_enclave_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product_enclave__department_id FOREIGN KEY (department_id) REFERENCES public.department(id),
	CONSTRAINT fk_product_enclave__landingzone_id FOREIGN KEY (landingzone_id) REFERENCES public.landingzone(id)
);


-- public.product_env definition

-- Drop table

-- DROP TABLE public.product_env;

CREATE TABLE public.product_env (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NULL,
	product_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT product_env_pkey PRIMARY KEY (id),
	CONSTRAINT fk_product_env__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);


-- public.cloud_element definition

-- Drop table

-- DROP TABLE public.cloud_element;

CREATE TABLE public.cloud_element (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	element_type varchar(255) NULL,
	hosted_services jsonb NULL,
	arn varchar(255) NULL,
	instance_id varchar(255) NULL,
	instance_name varchar(255) NULL,
	category varchar(20) NULL,
	landingzone_id int8 NULL,
	db_category_id int8 NULL,
	product_enclave_id int8 NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	cloud varchar(255) NULL,
	log_location varchar(255) NULL,
	trace_location varchar(255) NULL,
	metric_location varchar(255) NULL,
	service_category varchar(255) NULL,
	region varchar(255) NULL,
	log_group varchar(255) NULL,
	is_tagged bool DEFAULT false NULL,
	is_log_enabled bool DEFAULT false NULL,
	is_trace_enabled bool DEFAULT false NULL,
	is_event_enabled bool DEFAULT true NULL,
	CONSTRAINT cloud_element_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element__db_category_id FOREIGN KEY (db_category_id) REFERENCES public.db_category(id),
	CONSTRAINT fk_cloud_element__landingzone_id FOREIGN KEY (landingzone_id) REFERENCES public.landingzone(id),
	CONSTRAINT fk_cloud_element__product_enclave_id FOREIGN KEY (product_enclave_id) REFERENCES public.product_enclave(id)
);

-- public.cloud_element_cost definition

-- Drop table

-- DROP TABLE public.cloud_element_cost;

CREATE TABLE public.cloud_element_cost (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	cloud_element_id int8 NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	compliance_json jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT cloud_element_cost_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element_cost__cloud_element_id FOREIGN KEY (cloud_element_id) REFERENCES public.cloud_element(id)
);


-- public.cloud_element_summary definition

-- Drop table

-- DROP TABLE public.cloud_element_summary;

CREATE TABLE public.cloud_element_summary (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	summary_json jsonb NULL,
	landingzone_id int8 NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT cloud_element_summary_pkey PRIMARY KEY (id),
	CONSTRAINT fk_cloud_element_summary__landingzone_id FOREIGN KEY (landingzone_id) REFERENCES public.landingzone(id)
);


-- public."module" definition

-- Drop table

-- DROP TABLE public."module";

CREATE TABLE public."module" (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	"name" varchar(255) NOT NULL,
	product_id int8 NULL,
	product_env_id int8 NULL,
	service_topology jsonb NULL,
	metadata jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	module_nature varchar(20) NULL,
	CONSTRAINT module_pkey PRIMARY KEY (id),
	CONSTRAINT fk_module__product_env_id FOREIGN KEY (product_env_id) REFERENCES public.product_env(id),
	CONSTRAINT fk_module__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);


-- public.business_element definition

-- Drop table

-- DROP TABLE public.business_element;

CREATE TABLE public.business_element (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	service_name varchar(255) NOT NULL,
	service_nature varchar(20) NULL,
	service_type varchar(20) NULL,
	metadata jsonb NULL,
	cloud_element_id int8 NULL,
	department_id int8 NULL,
	product_id int8 NULL,
	module_id int8 NULL,
	product_env_id int8 NULL,
	sla_json jsonb NULL,
	cost_json jsonb NULL,
	view_json jsonb NULL,
	config_json jsonb NULL,
	compliance_json jsonb NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT business_element_pkey PRIMARY KEY (id),
	CONSTRAINT fk_business_element__cloud_element_id FOREIGN KEY (cloud_element_id) REFERENCES public.cloud_element(id),
	CONSTRAINT fk_business_element__department_id FOREIGN KEY (department_id) REFERENCES public.department(id),
	CONSTRAINT fk_business_element__module_id FOREIGN KEY (module_id) REFERENCES public."module"(id),
	CONSTRAINT fk_business_element__product_env_id FOREIGN KEY (product_env_id) REFERENCES public.product_env(id),
	CONSTRAINT fk_business_element__product_id FOREIGN KEY (product_id) REFERENCES public.product(id)
);


--update cloud_element set service_category = 'COMPUTE' where element_type in ('EC2','LAMBDA','ECS', 'EKS','BATCH','FARGATE');
--update cloud_element set service_category = 'STORAGE' where element_type in ('S3','EBS','EFS', 'GLACIER','STORAGE_GATEWAY');
--update cloud_element set service_category = 'NETWORK' where element_type in ('VPC','ROUTE53','DIRECT_CONNECT', 'VPN','GLOBAL_ACCELERATOR');
--update cloud_element set service_category = 'DATABASE' where element_type in ('RDS','AURORA','DYNAMODB', 'REDSHIFT','NEPTUNE','DOCUMENTDB');
--update cloud_element set service_category = 'OTHER' where element_type not in ('EC2','LAMBDA','ECS', 'EKS','BATCH','FARGATE','S3','EBS','EFS', 'GLACIER','STORAGE_GATEWAY', 'VPC','ROUTE53','DIRECT_CONNECT', 'VPN','GLOBAL_ACCELERATOR','RDS','AURORA','DYNAMODB', 'REDSHIFT','NEPTUNE','DOCUMENTDB');
--update product_enclave set service_category = 'NETWORK';

