CREATE TABLE public.config (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	"key" varchar(255) NULL,
	value varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	organization_id int8 NULL,
	CONSTRAINT config_pkey PRIMARY KEY (id),
	CONSTRAINT fk_config__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id)
);
CREATE TABLE public.cloud_element_supported_api (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	cloud varchar(255) NULL,
	element_type varchar(255) NULL,
    "name" varchar(255) NULL,
	status varchar(255) NULL default 'ACTIVE',
    created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT supported_element_api_pkey PRIMARY KEY (id)
);


