INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Apache Web Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'IIS Web Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Nginx Web Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'LiteSpeed Web Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Apache Tomcat', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Node.js', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Lighttpd', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'OpenLite Speed', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Jigsaw Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Sun Java System Web Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Java Spring Boot', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'NodeJS Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'GoLang Api Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Python Api Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'PHP Api Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Rails Api server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', '.Net Api Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Postgresql', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mysql', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mssql', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Orcale', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Dynamo', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mongodb', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'CouchDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Casandra', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Redis', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'MemCache', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Opensearch', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Ealsticsearch', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Neo4j', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'CosmosDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Amazon Neptune', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'AnzoGraphDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Datastax', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'DGraph', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'OrientDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'AWS kinesys', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Java Spring Boot Api Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'NodeJS Api Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'GoLang Api Server', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Python Api Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'PHP Api Server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Rails Api server', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Java Function in Lambda', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'NodeJS Function in Lambda', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'GoLang Function in Lambda', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Python Function in Lambda', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'PHP Function in Lambda', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Rails Function in Lambda', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Postgresql', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mysql', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mssql', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Orcale', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Dynamo', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mongodb', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'CouchDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Casandra', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Redis', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'MemCache', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Aurora', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'S3', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'CDN', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'GitHub', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Opensearch', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Ealsticsearch', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Neo4j', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'CosmosDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Amazon Neptune', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'AnzoGraphDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Datastax', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'DGraph', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'OrientDB', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'kinesis', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Firebase', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'WAF', 'DEACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'API Gw', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'Load Balancer', 'ACTIVE', current_timestamp, 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'APP', 'Java Spring Boot Api Server', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'DATA', 'Postgresql', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'OTHER', 'Ealsticsearch', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'WAF', 'DEACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'API Gw', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'Load Balancer', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SEARCH');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'APP', 'Java Spring Boot Api Server', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'DATA', 'Postgresql', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'OTHER', 'Ealsticsearch', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'WAF', 'DEACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'API Gw', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by, service_type, service_module) VALUES('SOA', 'PERIPHERAL', 'Load Balancer', 'ACTIVE', current_timestamp, 'System', 'COMMON', 'SECURITY');

