INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('APIGATEWAY', 'AWS', 'ACTIVE', current_timestamp, 'System', 'getApiGwList', 'getApiGwConfig', 'apiKey', true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('APPMESH', 'AWS', 'ACTIVE', current_timestamp, 'System', null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('ATHENA', 'AWS', 'ACTIVE', current_timestamp, 'System', null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('CDN', 'AWS', 'ACTIVE', current_timestamp, 'System', 'getCdnList', null, null, true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('CONFIGSERVICE', 'AWS', 'ACTIVE', current_timestamp, 'System', null, 'getDiscoveredResourceCounts', null, true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('DYNAMODB', 'AWS', 'ACTIVE', current_timestamp, 'System','getDynamoDbList', 'getDynamoDbConfig', 'tableName', true, 'DATABASE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('EC2', 'AWS', 'ACTIVE', current_timestamp, 'System','getEc2List', 'getEc2ConfigById', 'instanceId', true, 'COMPUTE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('ECS', 'AWS', 'ACTIVE', current_timestamp, 'System','getEcsList', 'getEcsConfig', 'clusterName', true, 'COMPUTE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('EKS', 'AWS', 'ACTIVE', current_timestamp, 'System','getEksList', 'getEksConfig', 'clusterName', true, 'COMPUTE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('ELASTICSEARCHSERVICE', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('ELBV2', 'AWS', 'ACTIVE', current_timestamp, 'System','getLbList', null, null, true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('GLACIER', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'STORAGE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('GLUE', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('IAM', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('KINESIS', 'AWS', 'ACTIVE', current_timestamp, 'System','getKinesisList', 'getKinesisConfig', 'streamName', true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('KMS', 'AWS', 'ACTIVE', current_timestamp, 'System','getKmsList', 'getKmsConfig', 'keyId', true, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('LAMBDA', 'AWS', 'ACTIVE', current_timestamp, 'System','getLambdaList', 'getLambdaConfig', 'functionName', true, 'COMPUTE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('MEMORYDB', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'DATABASE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('OPENSEARCHSERVICE', 'AWS', 'ACTIVE', current_timestamp, 'System',null, null, null, false, 'OTHER');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('RDS', 'AWS', 'ACTIVE', current_timestamp, 'System','getRdsList', 'getRdsConfig', 'arn', true, 'DATABASE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('S3', 'AWS', 'ACTIVE', current_timestamp, 'System','getS3List', 'getS3Config', 'bucketName', true, 'STORAGE');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('VPC', 'AWS', 'ACTIVE', current_timestamp, 'System','getVpcList', 'getVpcConfig', 'instanceId', true, 'NETWORK');
INSERT INTO public.cloud (element_type, "name", status, created_on, created_by, list_query, config_query, config_key, is_cron_scheduled, service_category) VALUES('WAF', 'AWS', 'ACTIVE', current_timestamp, 'System','getWafList', 'getWafConfig', 'instanceId', true, 'OTHER');


