CREATE TABLE bi_service (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	product_category varchar(255) NULL, -- 3 tier/soa
	service_category varchar(255) NULL, -- 3 tier (web/app/data/aux), soa (app/data/other)
	service_type varchar(255) NULL, -- soa (business/common)
	"name" varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT bi_service_pkey PRIMARY KEY (id)
);


