CREATE TABLE bi_service (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE),
	product_category varchar(255) NULL, -- 3 tier/soa
	service_category varchar(255) NULL, -- 3 tier (web/app/data/aux), soa (app/data/other)
	"name" varchar(255) NULL,
	status varchar(255) NULL,
	created_on timestamp NULL,
	updated_on timestamp NULL,
	updated_by varchar(255) NULL,
	created_by varchar(255) NULL,
	CONSTRAINT bi_service_pkey PRIMARY KEY (id)
);
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Apache Web Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'IIS Web Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Nginx Web Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'LiteSpeed Web Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Apache Tomcat', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Node.js', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Lighttpd', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'OpenLite Speed', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Jigsaw Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'WEB', 'Sun Java System Web Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Java Spring Boot', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'NodeJS Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'GoLang Api Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Python Api Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'PHP Api Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', 'Rails Api server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'APP', '.Net Api Server', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Postgresql', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mysql', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mssql', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Orcale', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Dynamo', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Mongodb', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'CouchDB', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Casandra', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'Redis', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'DATA', 'MemCache', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Opensearch', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Ealsticsearch', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Neo4j', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'CosmosDB', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Amazon Neptune', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'AnzoGraphDB', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'Datastax', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'DGraph', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'OrientDB', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('3 Tier', 'AUX', 'AWS kinesys', 'ACTIVE', '2024-02-23 12:47:58.835', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Java Spring Boot Api Server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'NodeJS Api Server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'GoLang Api Server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Python Api Server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'PHP Api Server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Rails Api server', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Java Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'NodeJS Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'GoLang Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Python Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'PHP Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'APP', 'Rails Function in Lambda', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Postgresql', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mysql', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mssql', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Orcale', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Dynamo', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Mongodb', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'CouchDB', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Casandra', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Redis', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'MemCache', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'Aurora', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'S3', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'CDN', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'DATA', 'GitHub', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Opensearch', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Ealsticsearch', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Neo4j', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'CosmosDB', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Amazon Neptune', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'AnzoGraphDB', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Datastax', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'DGraph', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'OrientDB', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'kinesys', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'OTHER', 'Firebase', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'WAF', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'API Gw', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');
INSERT INTO public.bi_service (product_category, service_category, "name", status, created_on, created_by) VALUES('SOA', 'PERIPHERAL', 'Load Balancer', 'ACTIVE', '2024-02-23 12:50:51.870', 'System');

