CREATE TABLE public.budget (
    id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    allocated_budget int8 NULL,
    budget_json jsonb NULL,
    status varchar(255) NULL,
    created_on timestamp NULL,
    created_by varchar(255) NULL,
    updated_on timestamp NULL,
    updated_by varchar(255) NULL,
    organization_id int8 NULL,
    CONSTRAINT budgett_pkey PRIMARY KEY (id)
);
ALTER TABLE public.budget ADD CONSTRAINT fk_budget__organization_id FOREIGN KEY (organization_id) REFERENCES public.organization(id);
